# .github/workflows/deploy.yml

name: Deploy VitePress site to Pages

on:
  # 在推送到默认分支（通常是 main 或 master）时触发
  push:
    branches: [main]

  # 允许手动在工作流选项卡中触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在运行的和最新队列之间的运行队列
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要此项

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # cache: pnpm # 根据你的包管理器改为 pnpm 或 yarn

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with VitePress
        run: pnpm run docs:build # 确保 package.json 中有这个脚本

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist # VitePress 默认输出目录

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
